Taverna to Pig Compiler

Generated Resources
===================

<tree>
Run Pig Script
==============

1) Please provide the required parameters in the pig param file '<pigParamFileName>'.

2) Please adjust the commands inside the python scripts if required.

3) Please make the python scripts executable: $ sudo chmod +x 'scripts/script_name'

4) To run the pig script on local mode:
	- $ sudo chmod +x run.sh
	- $ ./run.sh

5) To run the pig script on cluster mode:
	$ <pigRunClusterCommand>